CREATE SCHEMA IF NOT EXISTS manutencao;

CREATE TABLE IF NOT EXISTS manutencao.tecnico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    tecnico_categorias VARCHAR(255),
    imagem VARCHAR,
    perfil VARCHAR NOT NULL
);

INSERT INTO manutencao.tecnico (nome, email,senha,tecnico_categorias,imagem,perfil) VALUES ('admin', 'admin@mail','$2a$12$8aXrkS4knasDvbB5NNRa2eRmZZi1B/5l2mlvtG8Lsn3OFpyKjPy16','','','ADMIN');